import { fileURLToPath } from 'node:url';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { createDatabase } from './database.js';

/** SQL migrations generated by drizzle-kit (`npm run db:generate`). */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../../../migrations', import.meta.url));

/** Applies every pending migration to the database at `connectionString`. */
export async function runMigrations(connectionString: string): Promise<void> {
  const database = createDatabase(connectionString);
  try {
    await migrate(database.db, { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await database.close();
  }
}
